package selenium;



import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.base.Base;
import com.base.LoginAndlogOut;
import com.objectRepository.ComposeMailObject;

public class ComposeMail extends LoginAndlogOut{

	@Test()
	public void compose()
	{
		  ComposeMailObject sign1=PageFactory.initElements(driver,ComposeMailObject.class);
		  sign1.Compose.click();
		  Base.waitForElement(sign1.ToSent);
		  sign1.ToSent.sendKeys("mahanth.pachava@gmail.com");
		  sign1.subject.sendKeys("Sample Mail");
		  sign1.text.sendKeys("Hi," +
		  "This is Mahanth. This message is generated by selenium automation driver");
		  sign1.send.click(); 
		  String message="Sending...";
		  Base.waitForElement(sign1.Message); String expected=sign1.Message.getText();
		  Assert.assertEquals(message, expected);	
		
	  
		
	}

}
