package selenium;

import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.apache.poi.sl.usermodel.Sheet;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.base.Base;
import com.base.LoginAndlogOut;
import com.gargoylesoftware.htmlunit.javascript.host.dom.Document;
import com.objectRepository.ComposeMailObject;
import com.objectRepository.GmailLoginObject;
import com.objectRepository.SearchGoogle;
import com.utilities.ExcelRead;

public class Gmail extends LoginAndlogOut {

	@Test(priority = 1)
	public void gmailSearch() throws Exception {
		logger=reports.createTest("gmail search");
		SearchGoogle search = PageFactory.initElements(driver, SearchGoogle.class);
		
		String googlesearch=ExcelRead.getCellData("Gmail",1, 1);
		search.searchGoogleTextBox.sendKeys(googlesearch);
		  search.searchGoogleButton.click(); 
		  search.resultLink.click();
		  search.signIn.click();
		  
		 
	}

	@Test(priority = 2)
	public void login() throws Exception {
		logger=reports.createTest("login into Gmail");
		GmailLoginObject sign = PageFactory.initElements(driver, GmailLoginObject.class);
		System.out.println("login");
		Base.swtichTab();
		Base.waitForElement(sign.username);
		String username=ExcelRead.getCellData("Gmail", 4, 1);
		sign.username.sendKeys(username);
		sign.next.click();
		String password=ExcelRead.getCellData("Gmail", 5,1);
		sign.password.sendKeys(password);
		Base.waitForElement(sign.passwordNext);

	}
	
	
	/*
	 * @Test(priority=3,dependsOnMethods = {"login"}) public void compose() {
	 * ComposeMailObject
	 * sign1=PageFactory.initElements(driver,ComposeMailObject.class);
	 * sign1.Compose.click(); //((JavascriptExecutor)driver).executeScript(
	 * "arguments[0].value='mahanth.pachava@gmail.com';",
	 * "document.getElementById(':r0').style.display='none';");
	 * Base.waitForElement(sign1.ToSent);
	 * sign1.ToSent.sendKeys("mahanth.pachava@gmail.com");
	 * sign1.subject.sendKeys("Sample Mail"); sign1.text.sendKeys("Hi," +
	 * "This is Mahanth. This message is generated by selenium automation driver");
	 * sign1.send.click(); String message="Sending...";
	 * Base.waitForElement(sign1.Message); String expected=sign1.Message.getText();
	 * Assert.assertEquals(message, expected);
	 * 
	 * 
	 * Base.waitForElement(sign1.Message); String expected1=sign1.Message.getText();
	 * String message1="Message sent."; Assert.assertEquals(message1, expected1);
	 * 
	 * }
	 */
	
	/*
	 * @DataProvider(name="") public void getData1() { String sheetName="sheet1";
	 * int row=excel.getRows(sheetName); int colun=excel.getColumns(sheetName);
	 * 
	 * }
	 */
	
	
	/*
	 * @DataProvider(name = "getData")
	 *  public Object[][] getData() 
	 *  { String SheetName="Sheet2"; 
	 *  int row=excels.getRowCount(SheetName);
	 *   int col=excels.getColumnCount(SheetName);
	 *    System.out.println(row);
	 * System.out.println(col);
	 *  Object[][] data=new Object[row][col]; 
	 *  for(int rownum=0;rownum<row;rownum++) 
	 *  { 
	 *  for (int colNum=0;colNum<col;colNum++) 
	 *  {
	 * data[rownum][colNum]=excels.getFaceloginCredentials(SheetName,rownum,colNum);
	 *  } 
	 *  } 
	 *  return data;
	 * 
	 * }
	 */
	 
	}

